---
- name: Testing Variable Precedence 
  hosts: servera1.lab.example.com
  tasks:
    - name: Install {{ package }} package
      yum:
        name: "{{ package }}"
        state: present
      register: result

    - name: Show results
      debug:
        var: result.results
