---
- name: Config Web Server
  hosts: servera1.lab.example.com
  gather_facts: no
  tasks: 
    - name: installation
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: Dployment
      ansible.builtin.copy:
        content: " HelloWorld... Hello again"
        dest: /var/www/html/index.html
      notify:
        - restart_1

  handlers: 
    - name: restart_1 
      ansible.builtin.service:
        name: httpd
        state: restarted
